refactor: pre-release preparation

diff --git a/ci/build_and_publish_m2 b/ci/build_and_publish_m2
--- a/ci/build_and_publish_m2
+++ b/ci/build_and_publish_m2
@@ -11,28 +11,28 @@
 set -e
 
 version="$1"
-if [ -z "$version" ]; then
-    echo "missing version" >&2
-    echo "Usage: "$(basename "$0")" <version>" >&2
-    exit 1
+if [[ -z ${version} ]]; then
+	echo "missing version" >&2
+	echo "Usage: $(basename "$0") <version>" >&2
+	exit 1
 fi
-if ! grep -q "version = \"$VERSION\"" Cargo.toml; then
-    echo "version does not match Cargo.toml" >&2
-    exit 1
+if ! grep -q "version = \"${version}\"" Cargo.toml; then
+	echo "version does not match Cargo.toml" >&2
+	exit 1
 fi
 
 target=aarch64-apple-darwin
-cargo build --release --features --target $target
-BIN=target/$target/release/cargonode
-NAME=cargonode-$version-$target
-ARCHIVE="deployment/m2/$NAME"
+cargo build --release --target "${target}"
+BIN=target/${target}/release/cargonode
+NAME=cargonode-${version}-${target}
+ARCHIVE="deployment/m2/${NAME}"
 
-mkdir -p "$ARCHIVE"/{complete,doc}
-cp "$BIN" "$ARCHIVE"/
-strip "$ARCHIVE/cargonode"
-cp {README.md,LICENSE-MIT,LICENSE-APACHE} "$ARCHIVE"/
-cp {CHANGELOG.md} "$ARCHIVE"/doc/
+mkdir -p "${ARCHIVE}"/{complete,doc}
+cp "${BIN}" "${ARCHIVE}"/
+strip "${ARCHIVE}/cargonode"
+cp {README.md,LICENSE-MIT,LICENSE-APACHE} "${ARCHIVE}"/
+cp CHANGELOG.md "${ARCHIVE}"/doc/
 
-tar c -C deployment/m2 -z -f "$ARCHIVE.tar.gz" "$NAME"
-shasum -a 256 "$ARCHIVE.tar.gz" >"$ARCHIVE.tar.gz.sha256"
-gh release upload "$version" "$ARCHIVE.tar.gz" "$ARCHIVE.tar.gz.sha256"
+tar c -C deployment/m2 -z -f "${ARCHIVE}.tar.gz" "${NAME}"
+shasum -a 256 "${ARCHIVE}.tar.gz" >"${ARCHIVE}.tar.gz.sha256"
+gh release upload "${version}" "${ARCHIVE}.tar.gz" "${ARCHIVE}.tar.gz.sha256"
